### ISSUE TITLE
Error during shards install

### ISSUE THREAD

**Issue by gummybears** [viachpaliy/gtk_custom_widgets#2]
I am trying to build a gui and thought to use your shard. I  was able to run the samples from jhass
Using Crystal 0.34, linux mint 64 bits with libgirepository1.0-dev installed

shards.yml
````
name: test
version: 1.0.0

dependencies:
  gobject:
    github: jhass/crystal-gobject
    branch: v0.3.1

  gtk_custom_widgets:
    github: viachpaliy/gtk_custom_widgets
````
I am getting the following error
````
Resolving dependencies
Fetching https://github.com/jhass/crystal-gobject.git
Fetching https://github.com/viachpaliy/gtk_custom_widgets.git
Fetching https://github.com/viachpaliy/cairo-gobject.git
Unable to satisfy the following requirements:

- `gobject *` required by `shard.yml`
- `gobject ~> 0.8.0` required by `cairo-gobject 0.1.0+git.commit.5af0194ba3a8d0c5ab76f02069dcb540b443617e`
Failed to resolve dependencies
````
